package com.viafourasample.src.model

object IntentKeys {
    const val INTENT_STORY_PICTUREURL = "INTENT_STORY_PICTUREURL"
    const val INTENT_STORY_LINK = "INTENT_STORY_LINK"
    const val INTENT_STORY_TITLE = "INTENT_STORY_TITLE"
    const val INTENT_STORY_AUTHOR = "INTENT_STORY_AUTHOR"
    const val INTENT_STORY_CATEGORY = "INTENT_STORY_CATEGORY"
    const val INTENT_STORY_DESC = "INTENT_STORY_DESC"
    const val INTENT_CONTAINER_ID = "INTENT_CONTAINER_ID"
    const val INTENT_USER_UUID = "INTENT_CONTAINER_ID"
    const val INTENT_USER_PRESENTATION_TYPE = "INTENT_USER_PRESENTATION_TYPE"
    const val INTENT_NEW_COMMENT_ACTION = "INTENT_NEW_COMMENT_ACTION"
    const val INTENT_CONTAINER_TYPE = "INTENT_CONTAINER_TYPE"
    const val INTENT_NEW_COMMENT_CONTENT = "INTENT_NEW_COMMENT_CONTENT"
    const val INTENT_FOCUS_CONTENT_UUID = "INTENT_FOCUS_CONTENT_UUID"
}
